# Generated by Django 5.2.4 on 2025-07-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("birth_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RetirementScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_year", models.IntegerField(default=2025)),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married_filing_jointly", "Married Filing Jointly"),
                        ],
                        default="single",
                        max_length=50,
                    ),
                ),
                ("start_age", models.IntegerField(blank=True, null=True)),
                ("death_age", models.IntegerField(blank=True, null=True)),
                ("annual_income", models.TextField(default="[]")),
                ("annual_expenses", models.TextField(default="[]")),
                ("request_data", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yearly_data", models.TextField()),
                ("summary_stats", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="api.retirementscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashFlowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_age", models.IntegerField()),
                ("end_age", models.IntegerField()),
                (
                    "annual_adjustment",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.person",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_items",
                        to="api.retirementscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["start_age", "type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccountConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("401k", "401k"),
                            ("roth_ira", "Roth IRA"),
                            ("brokerage", "Brokerage"),
                            ("hsa", "HSA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("parameters", models.TextField(default="{}")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="api.retirementscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.person"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="api.retirementscenario",
                    ),
                ),
            ],
            options={
                "unique_together": {("scenario", "person")},
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("projection_run", "Projection Run"),
                            ("scenario_saved", "Scenario Saved"),
                            ("monte_carlo_run", "Monte Carlo Run"),
                            ("excel_export", "Excel Export"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
