# Generated by Django 5.2.4 on 2025-07-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetirementScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_age", models.IntegerField()),
                ("death_age", models.IntegerField()),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married_filing_jointly", "Married Filing Jointly"),
                        ],
                        default="single",
                        max_length=50,
                    ),
                ),
                ("annual_income", models.TextField()),
                ("annual_expenses", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yearly_data", models.TextField()),
                ("summary_stats", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="api.retirementscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("401k", "401k"),
                            ("roth_ira", "Roth IRA"),
                            ("brokerage", "Brokerage"),
                            ("hsa", "HSA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("parameters", models.TextField(default="{}")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="api.retirementscenario",
                    ),
                ),
            ],
        ),
    ]
