# Generated by Django 5.2.4 on 2025-07-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cashflowitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("current_age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("birth_year", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="retirementscenario",
            name="start_year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name="retirementscenario",
            name="annual_expenses",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="retirementscenario",
            name="annual_income",
            field=models.TextField(default="[]"),
        ),
        migrations.AlterField(
            model_name="retirementscenario",
            name="death_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="retirementscenario",
            name="start_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflowitem",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.person",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.person"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="api.retirementscenario",
                    ),
                ),
            ],
            options={
                "unique_together": {("scenario", "person")},
            },
        ),
    ]
