# Generated by Django 5.2.4 on 2025-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_person_retirementscenario_start_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirementscenario",
            name="request_data",
            field=models.TextField(default="{}"),
        ),
    ]
