# Generated by Django 5.2.4 on 2025-07-22 16:03

from django.db import migrations
from django.core.management import call_command


def setup_initial_data(apps, schema_editor):
    """Setup pricing tiers and Google OAuth with placeholder credentials"""
    # Setup pricing tiers
    call_command('setup_pricing_tiers')
    # Setup Google OAuth
    call_command('setup_google_oauth')


def reverse_setup_initial_data(apps, schema_editor):
    """Remove initial data (for migration rollback)"""
    SubscriptionTier = apps.get_model('payments', 'SubscriptionTier')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    
    # Remove tiers
    SubscriptionTier.objects.filter(name__in=['individual', 'professional']).delete()
    
    # Remove Google OAuth app
    SocialApp.objects.filter(provider='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),  # Ensure socialaccount tables exist
    ]

    operations = [
        migrations.RunPython(
            setup_initial_data, 
            reverse_setup_initial_data
        ),
    ]
