# Generated by Django 5.2.4 on 2025-07-22 16:03

from django.db import migrations
from django.core.management import call_command


def setup_initial_data(apps, schema_editor):
    """Setup pricing tiers and Google OAuth with placeholder credentials"""
    # Get the historical model
    SubscriptionTier = apps.get_model('payments', 'SubscriptionTier')
    
    # Create Individual tier
    SubscriptionTier.objects.get_or_create(
        name='individual',
        defaults={
            'display_name': 'Individual',
            'pricing_type': 'monthly',
            'price_monthly': 0,
            'price_annual': 0,  # This field still exists in migration 0002
            'pack_price': 0,
            'max_projection_runs': 3,
            'max_scenarios': 1,
            'max_monte_carlo_runs': 1,
            'max_simulations_per_run': 1000,
            'advanced_strategies': False,
            'multi_person_projections': False,
            'excel_export': False,
            'priority_support': False,
            'api_access': False,
            'household_locked': False,
            'is_active': True
        }
    )
    
    # Create Professional tier
    SubscriptionTier.objects.get_or_create(
        name='professional',
        defaults={
            'display_name': 'Professional',
            'pricing_type': 'monthly',
            'price_monthly': 200.00,
            'price_annual': 0,  # This field still exists in migration 0002
            'pack_price': 0,
            'max_projection_runs': 9999,
            'max_scenarios': 9999,
            'max_monte_carlo_runs': 9999,
            'max_simulations_per_run': 10000,
            'advanced_strategies': True,
            'multi_person_projections': True,
            'excel_export': True,
            'priority_support': True,
            'api_access': True,
            'household_locked': False,
            'is_active': True
        }
    )
    
    # Setup Google OAuth
    call_command('setup_google_oauth')


def reverse_setup_initial_data(apps, schema_editor):
    """Remove initial data (for migration rollback)"""
    SubscriptionTier = apps.get_model('payments', 'SubscriptionTier')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    
    # Remove tiers
    SubscriptionTier.objects.filter(name__in=['individual', 'professional']).delete()
    
    # Remove Google OAuth app
    SocialApp.objects.filter(provider='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),  # Ensure socialaccount tables exist
    ]

    operations = [
        migrations.RunPython(
            setup_initial_data, 
            reverse_setup_initial_data
        ),
    ]
