# Generated by Django 5.2.4 on 2025-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="max_projection_runs",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="projection_runs_used",
            field=models.IntegerField(default=0),
        ),
    ]
