# Generated by Django 5.2.4 on 2025-07-16 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_projection_runs_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="household_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="pack_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pack", "Pay-per-use Pack"),
                    ("monthly", "Monthly Subscription"),
                    ("annual", "Annual Subscription"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="stripe_price_id_pack",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="monte_carlo_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="projection_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="scenario_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("individual_pack", "Individual Pack"),
                    ("professional_monthly", "Professional Monthly"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="price_annual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("projection_run", "Projection Run"),
                    ("scenario_saved", "Scenario Saved"),
                    ("monte_carlo_run", "Monte Carlo Run"),
                    ("excel_export", "Excel Export"),
                    ("api_call", "API Call"),
                    ("pack_purchase", "Pack Purchase"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("annual", "Annual"),
                    ("pack", "Pack"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PackPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("projection_credits", models.IntegerField(default=0)),
                ("scenario_credits", models.IntegerField(default=0)),
                ("monte_carlo_credits", models.IntegerField(default=0)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.subscriptiontier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserHousehold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("household_data", models.TextField(default="{}")),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
