# Generated by Django 5.2.4 on 2025-07-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20250722_1603"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="price_annual",
        ),
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="stripe_price_id_annual",
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("individual_pack", "Individual Pack"),
                    ("professional", "Professional"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("pack", "Pay-per-use Pack"),
                    ("monthly", "Monthly Subscription"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("pack", "Pack")],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
