# Generated by Django 5.2.4 on 2025-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_add_pack_pricing_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("individual_pack", "Individual Pack"),
                    ("professional", "Professional"),
                    ("free", "Free"),
                    ("professional_monthly", "Professional Monthly"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
